version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: pixel_pay_db
    environment:
      POSTGRES_DB: pixel_pay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
